food_ordering_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path("",include("foodapp.urls")),
    

]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

foodapp/urls.py
from django.urls import path
from foodapp.views import *
app_name = "foodapp"

urlpatterns= [
	# client url
	path("home/", HomeView.as_view(),name="home"),

	# admin url
	#restaurant
	path("admin/home/", 
		AdminHomeView.as_view(),name="adminhome"),
	path('admin/restaurant-create/', 
		AdminRestaurantCreateView.as_view(), name='adminrestaurantcreate'),
	path('admin/restaurant-list/', 
		AdminRestaurantListView.as_view(), name = 'adminrestaurantlist'),
	path('admin/restaurant/<int:pk>/detail/', 
		AdminRestaurantDetailView.as_view(),name = 'adminrestaurantdetail'),
	path('admin/restaurant/<int:pk>/update/', 
		AdminRestaurantUpdateView.as_view(), name = 'adminrestaurantupdate'),
	path('admin/restaurant/<int:pk>/delete/', 
		AdminRestaurantDeleteView.as_view(), name = 'adminrestaurantdelete'),
	#slider
	path('admin/slider-create/', 
		AdminSliderBannerCreateView.as_view(), name = 'adminsliderbannercreate'),
	path('admin/slider-list/', 
		AdminSliderBannerListView.as_view(), name = 'adminsliderbannerlist'),
	# path('admin/slider/<int:pk>/delete/'AdminSliderBannerDetailView.as_view(),name = 'adminsliderbannerdetail'),
	path('admin/slider/<int:pk>/update/',
	 AdminSliderBannerUpdateView.as_view(), name = 'adminsliderbannerupdate'),
	path('admin/slider/<int:pk>/delete/', 
		AdminSliderBannerDeleteView.as_view(), name = 'adminsliderbannerdelete'),

	#category
	path('admin/category-create/',
		AdminCategoryCreateView.as_view(),name ='admincategorycreate'),
	path('admin/category-list/', 
		AdminCategoryListView.as_view(),name ='admincategorylist'),
	path('admin/category/<int:pk>/update/',
	 AdminCategoryUpdateView.as_view(),name ='admincategoryupdate'),
	path('admin/category/<int:pk>/delete/', 
		AdminCategoryDeleteView.as_view(),name ='admincategorydelete'),

	#fooditem
	path('admin/fooditem-create/',
		AdminFoodItemCreateView.as_view(),name='adminfooditemcreate'),
	path('admin/fooditem-list/',
		AdminFoodItemListView.as_view(),name='adminfooditemlist'),
	path('admin/fooditem/<int:pk>/update/',
		AdminFoodItemUpdateView.as_view(),name='adminfooditemupdate'),
	path('admin/fooditem/<int:pk>/delete/',
		AdminFoodItemDeleteView.as_view(),name='adminfooditemdelete'),

	#blogpost
	path('admin/blog-create/',
		AdminBlogCreateView.as_view(),name='adminblogcreate'),
	path('admin/blog-list/',
		AdminBlogListView.as_view(),name='adminbloglist'),
	path('admin/blog/<int:pk>/detail/',
		AdminBlogDetailView.as_view(),name='adminblogdetail'),

	# path('admin/blog-list/',
	# 	AdminBlogListView.as_view(),name='adminbloglist'),
	# path('admin/blog-list/',
	# 	AdminBlogListView.as_view(),name='adminbloglist'),
	

	


	
	
	

]

templates/admintemplates/adminhome.html
{% extends 'admintemplates/base.html' %}

{% load static %}

{% block content %}
<div class="page-wrapper" style="background-color: #a8aeb6;">
	<div class="container-fluid">
		<!-- Title -->
		<div class="row heading-bg">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
			  <h5 class="txt-dark">Admin Panel <a href="  "><strong>Orders</strong></a> | <a href="  "><small>Shipments</small></a></h5>
			</div>
			<!-- Breadcrumb -->
			<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
			  <ol class="breadcrumb">
				<li><a href="">Dashboard</a></li>
				<li class="active"><span>Order-Report</span></li>
				<!-- <li><a href="#"><span>product list</span></a></li> -->
			  </ol>
			</div>
			<!-- /Breadcrumb -->
		</div>
		<!-- /Title -->
		<h1>Welcome to Admin Dashboard</h1>
	</div>
</div>
{% endblock %}

templates/admintemplates/blogcreate.html
{% extends 'admintemplates/base.html' %}

{% load static %}
{% block title %}
Blog Create
{% endblock %}

{% block content %}

<div class="page-wrapper" style="background-color: #a8aeb6;">
	<div class="container-fluid">
		<!-- Title -->
		<div class="row heading-bg">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
			  <h5 class="txt-dark">Blog</h5>
			</div>
			<!-- Breadcrumb -->
			<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
			  <ol class="breadcrumb">
				<li><a href="">Dashboard</a></li>
				<li class="active"><span>Create Blog</span></li>
				<!-- <li><a href="#"><span>product list</span></a></li> -->
			  </ol>
			</div>
			<!-- /Breadcrumb -->
		</div>
		<!-- /Title -->
		<div class="row">
		    <div class="col-sm-12">
		        <div class="panel panel-default card-view">
		            <div class="panel-wrapper collapse in">
		                <div class="panel-body">
		                    <form method="POST" enctype="multipart/form-data">
		                    	<p class="text-danger">{{form.non_field_errors}}</p>
		                    	{% csrf_token %}
		                    	<h6 class="txt-dark capitalize-font"><i class="zmdi zmdi-info-outline mr-10"></i> Create Blog </h6>
		                    	<hr class="light-grey-hr"/>
		                    	<div class="row">
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Title</label>
		                    			{{form.title}}
		                    		</div>
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Description</label>
		                    			{{form.description}}
		                    		</div>
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Image</label>
		                    			{{form.image}}
		                    		</div>
		                    		
		                    	</div>
		                    	<!-- {{form.as_p}} -->
		                    	<button class="btn btn-success mt-10">Submit</button>
		                    </form>
		                </div>
		            </div>
		        </div>  
		    </div>
		</div>
		
	</div>
</div>
{% endblock %}

templates/admintemplates/categorycreate.html
{% extends 'admintemplates/base.html' %}

{% load static %}
{% block title %}
Category Create
{% endblock %}

{% block content %}

<div class="page-wrapper" style="background-color: #a8aeb6;">
	<div class="container-fluid">
		<!-- Title -->
		<div class="row heading-bg">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
			  <h5 class="txt-dark">Category</h5>
			</div>
			<!-- Breadcrumb -->
			<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
			  <ol class="breadcrumb">
				<li><a href="">Dashboard</a></li>
				<li class="active"><span>Create Category</span></li>
				<!-- <li><a href="#"><span>product list</span></a></li> -->
			  </ol>
			</div>
			<!-- /Breadcrumb -->
		</div>
		<!-- /Title -->
		<div class="row">
		    <div class="col-sm-12">
		        <div class="panel panel-default card-view">
		            <div class="panel-wrapper collapse in">
		                <div class="panel-body">
		                    <form method="POST" enctype="multipart/form-data">
		                    	<p class="text-danger">{{form.non_field_errors}}</p>
		                    	{% csrf_token %}
		                    	<h6 class="txt-dark capitalize-font"><i class="zmdi zmdi-info-outline mr-10"></i>Category</h6>
		                    	<hr class="light-grey-hr"/>
		                    	<div class="row">
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Title</label>
		                    			{{form.title}}
		                    		</div>
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Description</label>
		                    			{{form.description}}
		                    		</div>
		                    	</div>
		                    	<!-- {{form.as_p}} -->
		                    	<button class="btn btn-primary">Submit</button>
		                    </form>
		                </div>
		            </div>
		        </div>  
		    </div>
		</div>
		<!-- <div class="row">
			<div class="col-sm-12">
				<div class="panel panel-default card-view" style="background-color: transparent;">
						<div class="panel-wrapper collapse in">
						<div class="panel-body">
							<form method="POST" enctype="multipart/form-data">
								<p class="text-danger">{{form.non_field_errors}}</p>
								{% csrf_token %}
								{{form.as_p}}
								<button>Submit</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div> -->
	</div>
</div>
{% endblock %}

templates/admintemplates/categorylist.html
{% extends 'admintemplates/base.html' %}

{% load static %}
{% block content %}
<div class="page-wrapper" style="background-color: #a8aeb6;">
    <div class="container-fluid">
        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Category</h5>
            </div>
            <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
              <ol class="breadcrumb">
                <li><a href="">Dashboard</a></li>
                <li class="active"><span> List Category</span></li>
                <!-- <li><a href="#"><span>product list</span></a></li> -->
              </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
        <!-- /Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h6 class="panel-title txt-dark">Category</h6>
                        </div>
                        <div class="pull-right">
                            <h6 class="panel-title txt-dark"><a class="btn btn-success" href="{% url 'foodapp:admincategorycreate' %}">Add Category</a> </h6>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table id="example" class="table table-hover display pb-30" >
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Description</th>
                                                <th>Actions</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for category in categorylist %}
                                            <tr>
                                        
                                                <td>{{category.title}}</td>
                                                <td>{{category.description}}</td>
                                            
                                                <td>
                                                    <a href="{% url 'foodapp:admincategoryupdate' category.pk %}" class="btn btn-info">Update</a>
                                                     <a href="{% url 'foodapp:admincategorydelete' category.pk %}" class="btn btn-info">Delete</a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
<!--// main-heading -->




	
{% endblock %}

templates/admintemplates/fooditemcreate.html
{% extends 'admintemplates/base.html' %}

{% load static %}
{% block title %}
FoodItem Create

{% endblock %}

{% block content %}

<div class="page-wrapper" style="background-color: #a8aeb6;">
	<div class="container-fluid">
		<!-- Title -->
		<div class="row heading-bg">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
			  <h5 class="txt-dark">FoodItem</h5>
			</div>
			<!-- Breadcrumb -->
			<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
			  <ol class="breadcrumb">
				<li><a href="">Dashboard</a></li>
				<li class="active"><span>Create FoodItem</span></li>
				<!-- <li><a href="#"><span>product list</span></a></li> -->
			  </ol>
			</div>
			<!-- /Breadcrumb -->
		</div>
		<!-- /Title -->
		<div class="row">
		    <div class="col-sm-12">
		        <div class="panel panel-default card-view">
		            <div class="panel-wrapper collapse in">
		                <div class="panel-body">
		                    <form method="POST" enctype="multipart/form-data">
		                    	<p class="text-danger">{{form.non_field_errors}}</p>
		                    	{% csrf_token %}
		                    	<h6 class="txt-dark capitalize-font"><i class="zmdi zmdi-info-outline mr-10"></i>FoodItem</h6>
		                    	<hr class="light-grey-hr"/>
		                    	<div class="row">
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Name</label>
		                    			{{form.name}}
		                    		</div>
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Category</label>
		                    			{{form.category}}
		                    		</div>
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Photo</label>
		                    			{{form.photo}}
		                    		</div>
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Price</label>
		                    			{{form.price}}
		                    		</div>
		                    		<div class="col-md-12">
		                    			<label class="control-label mb-10">Description</label>
		                    			{{form.description}}
		                    		</div>
		                    	</div>
		                    	<!-- {{form.as_p}} -->
		                    	<button class="btn btn-success mt-10">Submit</button>
		                    </form>
		                </div>
		            </div>
		        </div>  
		    </div>
		</div>
		
	</div>
</div>
{% endblock %}

templates/admintemplates/fooditemlist.html
{% extends 'admintemplates/base.html' %}

{% load static %}
{% block content %}
<div class="page-wrapper" style="background-color: #a8aeb6;">
    <div class="container-fluid">
        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">FoodItem</h5>
            </div>
            <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
              <ol class="breadcrumb">
                <li><a href="">Dashboard</a></li>
                <li class="active"><span>FoodItem</span></li>
                <!-- <li><a href="#"><span>product list</span></a></li> -->
              </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
        <!-- /Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h6 class="panel-title txt-dark">FoodItem</h6>
                        </div>
                        <div class="pull-right">
                            <h6 class="panel-title txt-dark"><a class="btn btn-success" href="{% url 'foodapp:adminfooditemcreate' %}">Add FoodItem</a> </h6>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table id="example" class="table table-hover display pb-30" >
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Category</th>
                                                <th>Photo</th>
                                                <th>Price</th>
                                                <th>Description</th>
                                                <th>Actions</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for fooditem in fooditemlist %}
                                            <tr>
                                        
                                                <td>{{fooditem.name}}</td>
                                                <td>{{fooditem.category}}</td>
                                                <td>{{fooditem.photo}}</td>
                                                <td>{{fooditem.price}}</td>
                                                <td>{{fooditem.description}}</td>
                                                <td> <a href="{% url 'foodapp:adminfooditemupdate' fooditem.pk %}"class="btn btn-success">Update</a>
                                                    <a href="{% url 'foodapp:adminfooditemdelete' fooditem.pk %}"class="btn btn-success">Delete</a>
                                                   
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
<!--// main-heading -->




	
{% endblock %}

templates/admintemplates/restaurantdetail.html
{% extends 'admintemplates/base.html' %}
{% block title %}
Category Detail 
{% endblock %}

{% load static %}
{% block content %}

<div class="page-wrapper" style="background-color: #a8aeb6;">
    <div class="container-fluid">
        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Restaurant<h5>
            </div>
            <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
              <ol class="breadcrumb">
                <li><a href="">Dashboard</a></li>
                <li class="active"><span>List Restaurant</span></li>
                <!-- <li><a href="#"><span>product list</span></a></li> -->
              </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
        <!-- /Title -->
        <!-- <h1>Welcome to Admin Dashboard</h1> -->
        <div class="row">
            <!-- Stats -->
            <div class="outer-w3-agile col-xl">
                <div class="work-progres">
                    <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <!-- <div class="pull-left">
                            <h6 class="panel-title txt-dark">All Restaurant</h6>
                        </div>
                         <div class="pull-right">
                            <h6 class="panel-title txt-dark"><a class=" btn btn-success" href="{% url 'foodapp:adminrestaurantcreate' %}">Add Restaurant </a></h6>
                        </div> -->
                    
                    <hr>
                    <div class="table-responsive">
                        <table class=" table table table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th colspan="4" class="text-center">{{restaurantdetail.name}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th >Name</th>
                                    <td style="max-width: 200px;"> {{restaurantdetail.name}}</td>
                                    <th>Address</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.address}}</td>
                                </tr>
                                
                                <tr>
                                    <th>Logo</th>
                                    <td style="max-width: 200px;"><img src="{% if restaurantdetail.logo %} {{restaurantdetail.logo.url}} {% endif %}" alt="No Image"> </td>
                                    <th>Email</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.email}}</td>
                                </tr>
                                <tr>
                                    <th>Phone</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.phone}}</td>
                                    <th>About</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.about}}</td>
                                </tr>
                                 <tr>
                                    <th>Map Location</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.map_location}}</td>
                                    <th>Facebook</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.facebook}}</td>
                                </tr>
                                 <tr>
                                    <th>Instagram</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.instagram}}</td>
                                    <th>Youtube</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.youtube}}</td>
                                </tr>
                                 <tr>
                                    <th>Twitter</th>
                                    <td style="max-width: 200px;">{{restaurantdetail.twitter}}</td>
                                   
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!--// Stats -->
        </div>
    </div>
</div>

<!-- <h2 class="main-title-w3layouts mb-2 text-center">Restaurant </h2> -->
<!--// main-heading -->
<!-- <div class="container-fluid"> -->
<!-- </div> -->



	
{% endblock %}

templates/admintemplates/restaurantlist.html
{% extends 'admintemplates/base.html' %}

{% load static %}
{% block content %}

<div class="page-wrapper" style="background-color: #a8aeb6;">
    <div class="container-fluid">
        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Restaurant<h5>
            </div>
            <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
              <ol class="breadcrumb">
                <li><a href="">Dashboard</a></li>
                <li class="active"><span>List Restaurant</span></li>
                <!-- <li><a href="#"><span>product list</span></a></li> -->
              </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
        <!-- /Title -->
        <!-- <h1>Welcome to Admin Dashboard</h1> -->
        <div class="row">
            <!-- Stats -->
            <div class="outer-w3-agile col-xl">
                <div class="work-progres">
                    <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h6 class="panel-title txt-dark">All Restaurant</h6>
                        </div>
                         <div class="pull-right">
                            <h6 class="panel-title txt-dark"><a class=" btn btn-success" href="{% url 'foodapp:adminrestaurantcreate' %}">Add Restaurant </a></h6>
                        </div>
                    
                    <hr>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>logo</th>
                                    <th>Email</th>
                                    <!-- <th>Phone</th> -->
                                    <th>Address</th>
                                    <!-- <th>About</th>
                                    <th>Map Location</th>
                                    <th>Facebook</th>
                                    <th>Instagram</th>
                                    <th>Twitter</th>
                                    <th>Youtube</th> -->
                                    <th> Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            	{% for restaurant in restaurantlist %}
                                <tr>
                                    <td>{{restaurant.name}}</td>
                                    <td>{{restaurant.logo}}</td>
                                    <td>{{restaurant.email}}</td>
                                    <!-- <td>{{restuarant.phone}}</td> -->
                                    <td>{{restaurant.address}}</td>
                                    <!-- <td>{{restaurant.about}}</td>
                                    <td>{{restaurant.map_location}}</td>
                                    <td>{{restaurant.facebook}}</td>
                                    <td>{{restaurant.instagram}}</td>
                                    <td>{{restaurant.twitter}}</td>
                                    <td>{{restaurant.youtube}}</td> -->
                                    <td>
                                        <a href="{% url 'foodapp:adminrestaurantdetail' restaurant.pk %}" class="btn btn-info">Detail</a>
                                    	<a href="{% url 'foodapp:adminrestaurantupdate' restaurant.pk %}" class="btn btn-info">Update</a>
                                    	<a href="{% url 'foodapp:adminrestaurantdelete' restaurant.pk %}" class="btn btn-info">Delete</a>
                                    </td>
                                   
       
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!--// Stats -->
        </div>
    </div>
</div>

<!-- <h2 class="main-title-w3layouts mb-2 text-center">Restaurant </h2> -->
<!--// main-heading -->
<!-- <div class="container-fluid"> -->
<!-- </div> -->



	
{% endblock %}

templates/admintemplates/sliderbannerlist.html
{% extends 'admintemplates/base.html' %}

{% load static %}
{% block content %}
<div class="page-wrapper" style="background-color: #a8aeb6;">
    <div class="container-fluid">
        <!-- Title -->
        <div class="row heading-bg">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h5 class="txt-dark">Slider</h5>
            </div>
            <!-- Breadcrumb -->
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
              <ol class="breadcrumb">
                <li><a href="">Dashboard</a></li>
                <li class="active"><span>Slider</span></li>
                <!-- <li><a href="#"><span>product list</span></a></li> -->
              </ol>
            </div>
            <!-- /Breadcrumb -->
        </div>
        <!-- /Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default card-view">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h6 class="panel-title txt-dark">Slider</h6>
                        </div>
                        <div class="pull-right">
                            <h6 class="panel-title txt-dark"><a class="btn btn-success" href="{% url 'foodapp:adminsliderbannercreate' %}">add slider</a> </h6>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table id="example" class="table table-hover display pb-30" >
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Caption</th>
                                                <th>Image</th>
                                                <th>Actions</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for slider in sliderbannerlist %}
                                            <tr>
                                        
                                                <td>{{slider.title}}</td>
                                                <td>{{slider.caption}}</td>
                                                <td>{{slider.image}}</td>
                                                <td>
                                                    <a href="{% url 'foodapp:adminsliderbannerupdate' slider.pk %}" class="btn btn-info">Update</a>
                                                     <a href="{% url 'foodapp:adminsliderbannerdelete' slider.pk %}" class="btn btn-info">Delete</a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
<!--// main-heading -->




	
{% endblock %}